### ISSUE TITLE
openfire server windows server and wss 

### ISSUE THREAD

**Issue by thevietnamm** [igniterealtime/webmeet#3]
how can I change the bosch and ws address of webmeet to openfire windows server

**Comment by deleolajide** [comment]
See https://github.com/igniterealtime/webmeet#additional-considerations

**Comment by AndresTC93** [comment]
@deleolajide i already configured this but not is posible conect to ws but to bosch connect perfect sorry my bad english

**Comment by deleolajide** [comment]
It depends on what Openfire server you are using. WebSocket is standard in OF 4.2.x, but if you are using an older version, you will need the websocket plugin

**Comment by AndresTC93** [comment]
@deleolajide I have exactly version 4.2.3 but I have not managed to configure it correctly, you could help me via team viewer I'm really novice in this

**Comment by deleolajide** [comment]
Sorry, I have a customer deadline and not available. Make sure you have the trailing slash "/"
````
websocket_url: 'wss://traderlynk.4ng.net/ws/',
````

**Comment by AndresTC93** [comment]
![imagen](https://user-images.githubusercontent.com/38565800/40723770-37de26b8-63e5-11e8-842d-7fe322d571c5.png)

this is my config

**Comment by deleolajide** [comment]
auto_join_rooms should be ['lobby@conference.emlazesystems.co']
websocket_url should be 'wss://.emlazesystems.co:7443/ws/'
